[package]
name = "course-achievements"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.11.0"

[dev-dependencies]
soroban-sdk = { version = "0.11.0", features = ["testutils"] }