version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Collector (jaeger thrift http)
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
